kind: pipeline
name: build

steps:
  - name: frontend
    image: node
    commands:
      - cd dashboard
      - npm install
      - npm run build
    environment:
      CI: false

  - name: backend
    image: golang
    commands:
      - go get github.com/GeertJohan/go.rice/rice
      - cd server
      - rice embed-go
      - cd ..
      - go build
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
